const PRODUCTS = [
    {
        id: 1,
        name: "Мужские Кроссовки Nike Air Max 270",
        preview: "https://cdn.sportmaster.ru/upload/resize_cache/iblock/ca8/800_800_1/52336510299.jpg",
        price: 12999,
    },
    {
        id: 2,
        name: "Мужские Кроссовки Nike Blazer Mid Suede",
        preview: "https://www.basketshop.ru/files/catalog/38278/CI1172-002(9).JPG",
        price: 8499,
    },
    {
        id: 3,
        name: "Кроссовки Puma X Aka Boku Future Rider",
        preview: "https://footboxshop.ru/upload/iblock/353/mt9o4dq1putpgx484udgpulw63am3s26.jpg",
        price: 8799,
    },
    {
        id: 4,
        name: "Мужские Кроссовки Nike Kyrie Flytrap IV",
        preview: "https://www.basketshop.ru/files/catalog/43184/CT1973-101(1).JPG",
        price: 11299,
    },
    {
        id: 5,
        name: "Мужские Кроссовки Nike Blazer Mid Suede",
        preview: "https://sneakersearch.ru/wp-content/uploads/2021/05/CI1172004-sneaker-search.jpg",
        price: 6999,
    },
    {
        id: 6,
        name: "Мужские Кроссовки Jordan Air Jordan 11",
        preview: "https://www.спортдлявсех.рус/2474-medium_default/krossovki-air-jordan-11-cmft-low.jpg",
        price: 10799,
    },
];

export default PRODUCTS;